    import java.awt.event.*;
    import java.awt.Color;
    import javax.swing.*;
    
    
public class frmSplash extends javax.swing.JFrame {
    Timer timLoad,timImg;
    int val = 0,fil=0;
    frmOrganization frmmain;
    public frmSplash() {
        initComponents();
                getContentPane().setBackground(Color.BLUE);
            timLoad =new Timer (90,new ActionListener()            
            {
            public void actionPerformed(ActionEvent evt)
            {
            pbLoading.setValue(val++);
            if(val<10)
                lblWord.setText("Initializing.....");
            else if(val<20)
                lblWord.setText("Readng Database.....");
            else if(val<30)
                lblWord.setText("Loading Database.....");
            else if(val<40)
                lblWord.setText("Preparing to start Database.....");
            else if(val<40)
                lblWord.setText("Turning on Database.....");
            else if(val<50)
                lblWord.setText("Starting Database.....");
            else if(val<60)
                lblWord.setText("Prepared Database.....");
            else if(val<70)
                lblWord.setText("Opening Database.....");
            else if(val<80)
                lblWord.setText("Connecting Database.....");
            else if(val<90)
                lblWord.setText("Completed Opening Database.....");
            else
                lblWord.setText("Done....");
            if(val==101)
            {
                timLoad.stop();
                dispose();
                frmmain = new frmOrganization();
                frmmain.setVisible(true);
                frmmain.pack();
            }
            }
            });
            timImg=new Timer(100,new ActionListener(){
            
                public void actionPerformed(ActionEvent evt)
                {
                    lblImage.setIcon(new ImageIcon("C:\\Users\\Devesh\\Documents\\NetBeansProjects\\Payroll\\src\\Splash\\"+(++fil)+".jpg"));
                    if(fil==35)
                    {
                        fil=0;
                     
                    }
                }
            
            });
        timLoad.start();
        timImg.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        pbLoading = new javax.swing.JProgressBar();
        lblWord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        lblImage.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(lblWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pbLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWord, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(574, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblWord;
    private javax.swing.JProgressBar pbLoading;
    // End of variables declaration//GEN-END:variables
}
